spring:
  application:
    name: shop-with-me
  datasource:
    url: jdbc:mariadb://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 2010
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2Hrs
    refreshTokenExpiration: 604800 #7days

stripe:
  secretKey:${STRIPE_SECRET_KEY}