-- Insert Categories (IDs generated automatically)
INSERT INTO categories (name)
VALUES ('Electronics & Mobile'),
       ('Home & Kitchen Appliances'),
       ('Groceries & Foodstuffs'),
       ('Fashion & Apparel'),
       ('Beauty & Personal Care'),
       ('Construction & Hardware'),
       ('Automotive & Motorbike');

-- Insert 40 Products (IDs generated automatically, category_id fetched dynamically)
INSERT INTO products (name, price, description, category_id)
VALUES

-- Category 1: Electronics & Mobile
('Samsung Galaxy A15 (128GB, 6GB RAM)', 510000.00,
 'Dual SIM Android smartphone with 6.5-inch Super AMOLED screen, 50MP main camera, and 5000mAh battery.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),
('TCL 43-inch Smart Android TV', 579000.00,
 'Full HD LED Smart TV featuring built-in Chromecast, Google Assistant, Dolby Audio, and Wi-Fi.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),
('Starlink Standard Satellite Kit V2', 1050000.00,
 'High-speed, low-latency satellite internet receiver and router kit for residential or business connectivity.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),
('Tecno Spark 20 (256GB, 8GB RAM)', 410000.00,
 'Budget-friendly 4G smartphone featuring 90Hz refresh rate, 50MP glow camera, and 18W fast charging.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),
('Oraimo FreePods Lite Wireless Earbuds', 50000.00,
 'Bluetooth 5.3 in-ear headphones with 40-hour playtime, heavy bass drivers, and low-latency game mode.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),
('Apple iPhone 13 (128GB, Midnight)', 1350000.00,
 '6.1-inch Super Retina XDR display, A15 Bionic chip, advanced dual-camera system with Cinematic mode.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),
('Anker 20,000mAh Power Bank 15W', 95000.00,
 'High-capacity portable charger with PowerIQ technology, dual USB output ports, and trickling charge feature.',
 (SELECT id FROM categories WHERE name = 'Electronics & Mobile')),

-- Category 2: Home & Kitchen Appliances
('Von 16-inch Solar Powered Standing Fan', 125000.00,
 'Rechargeable 16-inch standing fan with solar panel input, 3 speed settings, and emergency LED night light.',
 (SELECT id FROM categories WHERE name = 'Home & Kitchen Appliances')),
('Midea 2-Burner Tabletop Gas Cooker', 85000.00,
 'Stainless steel LPG gas stove with auto-ignition, heavy-duty pan support, and energy-efficient burners.',
 (SELECT id FROM categories WHERE name = 'Home & Kitchen Appliances')),
('Westpoint Citrus Juicer 20W 0.5L', 59000.00,
 'Compact electric juicer with dual-direction rotation cone, pulp adjuster, and detachable juice container.',
 (SELECT id FROM categories WHERE name = 'Home & Kitchen Appliances')),
('Bruhm 90L Single Door Mini Fridge', 420000.00,
 'Compact refrigerator with small freezer compartment, mechanical temperature control, and low noise design.',
 (SELECT id FROM categories WHERE name = 'Home & Kitchen Appliances')),
('Ramtons 1.7L Electric Stainless Steel Kettle', 45000.00,
 'Fast-boiling cordless kettle with automatic shut-off, dry-boil protection, and removable filter.',
 (SELECT id FROM categories WHERE name = 'Home & Kitchen Appliances')),
('Decakila 800W Electric Microwave Oven 20L', 210000.00,
 'Countertop microwave with 5 power levels, defrost setting, 35-minute timer, and glass turntable.',
 (SELECT id FROM categories WHERE name = 'Home & Kitchen Appliances')),

-- Category 3: Groceries & Foodstuffs
('Azam Wheat Flour (Ngano) - 2kg Pack', 4500.00,
 'Premium quality refined wheat flour ideal for baking chapati, mandazi, and home baking.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),
('Kilombero Pure White Rice - 10kg Bag', 32000.00,
 'Aromatic long-grain Grade-1 Kilombero white rice sourced directly from Morogoro farms.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),
('Korie Pure Vegetable Cooking Oil - 5 Liters', 28500.00,
 'Refined palm cooking oil fortified with Vitamin A. Heat-stable for frying and everyday cooking.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),
('Mo Extra Soft Toilet Paper (Pack of 10)', 8500.00,
 '100% virgin pulp 2-ply soft toilet paper rolls manufactured locally by METL group.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),
('Azam Premium Pure Sugar - 5kg Bag', 16500.00,
 'Crystalline white refined sugar produced locally in Tanzania for household sweetening needs.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),
('Mo Energy Drink 300ml (Pack of 24 Cans)', 22000.00,
 'Refreshing caffeinated carbonated energy drink, packed in a 24-can bulk wholesale tray.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),
('Kili Black Tea Bags - 100 Count Box', 6500.00,
 'Pure Tanzanian black tea leaves harvested from the slopes of Mount Kilimanjaro.',
 (SELECT id FROM categories WHERE name = 'Groceries & Foodstuffs')),

-- Category 4: Fashion & Apparel
('Original Kitenge African Wax Fabric (6 Yards)', 35000.00,
 'High-grade 100% cotton printed African wax fabric (Kitenge) suitable for custom dresses and suits.',
 (SELECT id FROM categories WHERE name = 'Fashion & Apparel')),
('Men Genuine Leather Maasai Sandals', 25000.00,
 'Handcrafted leather sandals made in Arusha with traditional beaded accents and durable rubber soles.',
 (SELECT id FROM categories WHERE name = 'Fashion & Apparel')),
('Kangas Pair (2 Pieces) with Swahili Sayings', 22000.00,
 'Traditional 100% cotton printed Kangas featuring classic Swahili proverbs (Msemo) along the borders.',
 (SELECT id FROM categories WHERE name = 'Fashion & Apparel')),
('Safari Leather Boots for Men', 85000.00,
 'Durable brown suede outdoor boots with thick tread soles, ideal for walking and safari wear.',
 (SELECT id FROM categories WHERE name = 'Fashion & Apparel')),
('Women Printed Cotton Batani Dress', 30000.00,
 'Lightweight, breathable summer cotton dress tailored with vibrant local prints.',
 (SELECT id FROM categories WHERE name = 'Fashion & Apparel')),

-- Category 5: Beauty & Personal Care
('Wholesome Luxe Cocoa Butter Body Lotion (400ml)', 18000.00,
 'Deep moisturizing skin lotion enriched with natural cocoa butter and Vitamin E for daily use.',
 (SELECT id FROM categories WHERE name = 'Beauty & Personal Care')),
('Sheth Naturals Raw Unrefined Shea Butter (250g)', 22000.00,
 'Organic African shea butter ideal for natural hair moisture retention and sensitive skin hydration.',
 (SELECT id FROM categories WHERE name = 'Beauty & Personal Care')),
('Nivea Men Fresh Active Roll-On (50ml)', 7500.00,
 '48-hour antiperspirant deodorant roll-on infused with ocean extracts for lasting freshness.',
 (SELECT id FROM categories WHERE name = 'Beauty & Personal Care')),
('Dettol Herbal Antibacterial Soap Bar (125g)', 2500.00,
 'Hygiene soap formulated with botanical extracts for daily germ protection and skin freshness.',
 (SELECT id FROM categories WHERE name = 'Beauty & Personal Care')),
('Nice & Lovely Herbal Hair Food (150g)', 6000.00,
 'Enriched with avocado oil and Vitamin E to soothe dry scalp and promote healthy hair growth.',
 (SELECT id FROM categories WHERE name = 'Beauty & Personal Care')),
('Lattafa Khamrah Eau De Parfum (100ml)', 85000.00,
 'Long-lasting unisex oriental fragrance featuring warm spicy notes, vanilla, and sweet amber.',
 (SELECT id FROM categories WHERE name = 'Beauty & Personal Care')),

-- Category 6: Construction & Hardware
('Simba Cement 42.5N High Strength (50kg Bag)', 21500.00,
 'Portland Pozzolana Cement suitable for heavy structural concrete work, columns, and foundations.',
 (SELECT id FROM categories WHERE name = 'Construction & Hardware')),
('Twiga Extra Cement 32.5R (50kg Bag)', 19500.00,
 'General-purpose building cement designed for bricklaying, plastering, and non-structural concreting.',
 (SELECT id FROM categories WHERE name = 'Construction & Hardware')),
('DeWalt 20V Max Cordless Drill Driver Kit', 380000.00,
 'Compact brushless power drill with 2 lithium-ion batteries, charger, and sturdy carry kit.',
 (SELECT id FROM categories WHERE name = 'Construction & Hardware')),
('Corrugated Iron Roofing Sheets (30 Gauge - 3m)', 28000.00,
 'Galvanized iron roofing sheets designed to withstand tropical weather and resist rust.',
 (SELECT id FROM categories WHERE name = 'Construction & Hardware')),
('Sun King Home 200 Solar Light & Phone Charger System', 210000.00,
 'Off-grid solar system with 3 overhead LED lamps, USB multi-head phone charger, and solar panel.',
 (SELECT id FROM categories WHERE name = 'Construction & Hardware')),

-- Category 7: Automotive & Motorbike
('Boxer BM 150 Motorcycle Tubeless Rear Tire', 65000.00,
 'Heavy-duty rear tire manufactured for popular commercial motorcycle (Bodaboda) models.',
 (SELECT id FROM categories WHERE name = 'Automotive & Motorbike')),
('Total Quartz 5000 Engine Oil 20W-50 (4 Liters)', 58000.00,
 'Premium mineral engine oil protecting high-mileage gasoline and diesel engines from wear.',
 (SELECT id FROM categories WHERE name = 'Automotive & Motorbike')),
('Yuasa 12V 70Ah Maintenance-Free Car Battery', 240000.00,
 'Reliable automotive starter battery built for tropical heat and frequent city driving.',
 (SELECT id FROM categories WHERE name = 'Automotive & Motorbike')),
('Portable Digital Tire Inflator & Air Pump 12V', 75000.00,
 '12V cigarette-lighter powered tire pump with LED pressure readout and auto shut-off.',
 (SELECT id FROM categories WHERE name = 'Automotive & Motorbike'));